In [5]:
import numpy as np
import random
import copy

In [6]:
moves=[]
dimension=int(input("Enter dimension of box"))
matrix = np.zeros((dimension, dimension), dtype=int)
f=1

In [7]:
def Right(matrix):
    end=len(matrix)-1
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            if matrix[i][len(matrix)-1-j]!=0:
                temp=matrix[i][len(matrix)-1-j]
                matrix[i][len(matrix)-1-j]=0
                matrix[i][end]=temp
                end-=1
        end=len(matrix)-1

def Left(matrix):
    start=0
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            if matrix[i][j]!=0:
                temp=matrix[i][j]
                matrix[i][j]=0
                matrix[i][start]=temp
                start+=1
        start=0

def Up(matrix):
    start=0
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            if matrix[j][i]!=0:
                temp=matrix[j][i]
                matrix[j][i]=0
                matrix[start][i]=temp
                start+=1
        start=0

def Down(matrix):
    end=len(matrix)-1
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            if matrix[len(matrix)-j-1][i]!=0:
                temp=matrix[len(matrix)-j-1][i]
                matrix[len(matrix)-j-1][i]=0
                matrix[end][i]=temp
                end-=1
        end=len(matrix)-1

def randomAdd(matrix):
        col=random.randint(0,len(matrix)-1)
        row=random.randint(0,len(matrix)-1)
        while matrix[row][col]!=0:
            row=random.randint(0,len(matrix)-1)
            col=random.randint(0,len(matrix)-1)
        matrix[row][col]=random.choice([2,4])

def AddRight(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix)-1):
            if(matrix[i][len(matrix)-1-j]==matrix[i][len(matrix)-2-j]):
                matrix[i][len(matrix)-1-j]*=2
                for k in range(len(matrix)-2-j,-1,-1):
                    if(k!=0):
                        matrix[i][k]=matrix[i][k-1]
                    else:
                        matrix[i][k]=0

def AddLeft(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix)-1):
            if(matrix[i][j]==matrix[i][j+1]):
                matrix[i][j]*=2
                for k in range(j+1,len(matrix)):
                    if(k!=len(matrix)-1):
                        matrix[i][k]=matrix[i][k+1]
                    else:
                        matrix[i][k]=0

def AddDown(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix)-1):
            if(matrix[len(matrix)-1-j][i]==matrix[len(matrix)-2-j][i]):
                matrix[len(matrix)-1-j][i]*=2
                for k in range(len(matrix)-2-j,-1,-1):
                    if(k!=0):
                        matrix[k][i]=matrix[k-1][i]
                    else:
                        matrix[k][i]=0

def AddUp(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix)-1):
            if(matrix[j][i]==matrix[j+1][i]):
                matrix[j][i]*=2
                for k in range(j+1,len(matrix)):
                    if(k!=len(matrix)-1):
                        matrix[k][i]=matrix[k+1][i]
                    else:
                        matrix[k][i]=0

def Over(matrix):
    mat=copy.deepcopy(matrix)
    AddDown(mat)
    AddUp(mat)
    AddRight(mat)
    AddLeft(mat)
    for i in range(len(mat)):
        for j in range(len(mat)):
            if(mat[i][j]==0):
                return 0
    return 1

def Is_full(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            if(matrix[i][j]==0):
                return 0
    return 1

def Won(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            if(matrix[i][j]==2048):
                return 1
    return 0



In [8]:
for i in range(2):
    randomAdd(matrix)

print(matrix)
print("\n")

while f==1:
    order=input("Enter D for Right, A for Left, W for Up, S for down, 0 to exit")
    if(order=='D'):
        Right(matrix)
        AddRight(matrix)
        moves.append("Right")
    elif(order=='A'):
        Left(matrix)
        AddLeft(matrix)
        moves.append("Left")
    elif(order=='W'):
        Up(matrix)
        AddUp(matrix)
        moves.append("Up")
    elif(order=='S'):
        Down(matrix)
        AddDown(matrix)
        moves.append("Down")
    elif(order=='0'):
        f=0
    if Is_full(matrix)==0:
        randomAdd(matrix)
    if(Over(matrix)==1):
        print("Game Over")
        f=0
    if(Won(matrix)==1):
        print("Congratulation! You won...")
        f=0
    print(matrix)
    print("\n")

print(f"Set of optimal moves to win:\n{moves}")

[[0 2 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 4 0]]


[[2 2 4 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


[[0 4 4 4]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


[[0 4 4 4]
 [0 0 0 0]
 [0 0 0 0]
 [2 0 0 0]]


Set of optimal moves to win:
['Up', 'Right']
